# Generated by Django 4.2.1 on 2023-06-07 08:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
